spring:
  application:
    name: cloud-send-email-service
  cloud:
    nacos:
      discovery:
        server-addr: 182.92.219.19:8848
  rabbitmq:
    host: 182.92.219.19
    username: guest
    password: guest
    virtual-host: /
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 2248005433@qq.com #QQ邮箱
    password: mfnacdicpsppebfd #客户端授权码
    protocol: smtp #发送邮件协议
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.display.sendmail: Javen #可以任意
    properties.mail.display.sendname: Spring Boot Guide Email #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
    from: 2248005433@qq.com
management:
  endpoints:
    web:
      exposure:
        include: "*"
swagger2:
  doc:
    title: 图片上传服务文档
    desc: 图片上传Api
    basePackage: com.akali.cloud
